### ISSUE TITLE
Conversation 1 is missing user statements after the first one

### ISSUE THREAD

**Issue by ccjernigan** [rb81/health-coaching-conversations#1]
Reviewing this file: https://github.com/rb81/health-coaching-conversations/blob/main/conversations/01.json

Notice only the first statement is from a user, although alternating between user and assistant is expected.

**Comment by rb81** [comment]
Thanks, @ccjernigan. I don't know what happened there. Restored the missing user messages in https://github.com/rb81/health-coaching-conversations/commit/f59bdab49129a30fa47aa271bcb6374b63cef074.
